In [1]:
import pandas as pd
import numpy as np

In [2]:
from time import time
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [3]:
data = pd.read_csv(r'C:\Users\bala.vivek\Desktop\houseprice\imdb\Train.csv')

In [4]:
data.shape

(40000, 2)

In [5]:
data.isnull().sum()

text     0
label    0
dtype: int64

In [4]:
data = data[39500:]

In [5]:
data.shape

(500, 2)

In [14]:
from sklearn.model_selection import train_test_split

In [6]:
x=data['text']
y=data['label']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

<IPython.core.display.Javascript object>

In [8]:
tf_vectorizer=TfidfVectorizer()

In [9]:
x_train_tf=tf_vectorizer.fit_transform(x_train)

In [10]:
x_test_tf= tf_vectorizer.transform(x_test)

In [11]:
x_test_tf

<150x10416 sparse matrix of type '<class 'numpy.float64'>'
	with 16971 stored elements in Compressed Sparse Row format>

In [12]:
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(x_train_tf, y_train)

MultinomialNB()

In [13]:
y_pred = naive_bayes_classifier.predict(x_test_tf)

In [14]:
score1= metrics.accuracy_score(y_test,y_pred)

In [15]:
score1

0.72

In [16]:
print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.66      0.88      0.75        73
    Negative       0.83      0.57      0.68        77

    accuracy                           0.72       150
   macro avg       0.74      0.72      0.71       150
weighted avg       0.75      0.72      0.71       150



In [17]:
print(metrics.confusion_matrix(y_test, y_pred))

[[64  9]
 [33 44]]


In [18]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier()
rf.fit(x_train_tf,y_train)

RandomForestClassifier()

In [22]:
y_pred = rf.predict(x_test_tf)

In [23]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [24]:
score=metrics.accuracy_score(y_test,y_pred)

In [25]:
score

0.7466666666666667

In [26]:
scores = cross_val_score(rf,x_train_tf,y_train,cv=5)

<IPython.core.display.Javascript object>

In [27]:
scores

array([0.68571429, 0.67142857, 0.67142857, 0.65714286, 0.65714286])

In [30]:
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier()
parameters = {
    'n_estimators': [5,50,100],
    'max_depth': [2,10,20,None]
}

cv = GridSearchCV(rf,parameters)
cv.fit(x_train_tf,y_train)
print_results(cv)

BEST PARAMS: {'max_depth': 2, 'n_estimators': 100}

0.6 (+/-0.094) for {'max_depth': 2, 'n_estimators': 5}
0.666 (+/-0.111) for {'max_depth': 2, 'n_estimators': 50}
0.7 (+/-0.108) for {'max_depth': 2, 'n_estimators': 100}
0.537 (+/-0.059) for {'max_depth': 10, 'n_estimators': 5}
0.651 (+/-0.097) for {'max_depth': 10, 'n_estimators': 50}
0.697 (+/-0.046) for {'max_depth': 10, 'n_estimators': 100}
0.6 (+/-0.075) for {'max_depth': 20, 'n_estimators': 5}
0.697 (+/-0.095) for {'max_depth': 20, 'n_estimators': 50}
0.691 (+/-0.056) for {'max_depth': 20, 'n_estimators': 100}
0.591 (+/-0.071) for {'max_depth': None, 'n_estimators': 5}
0.646 (+/-0.093) for {'max_depth': None, 'n_estimators': 50}
0.7 (+/-0.085) for {'max_depth': None, 'n_estimators': 100}


In [29]:
def print_results(results):
    print('BEST PARAMS: {}\n'.format(results.best_params_))

    means = results.cv_results_['mean_test_score']
    stds = results.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, results.cv_results_['params']):
        print('{} (+/-{}) for {}'.format(round(mean, 3), round(std * 2, 3), params))

AttributeError: 'DataFrame' object has no attribute 'count_values'